### ISSUE TITLE
Image not uploading on IE11

### ISSUE THREAD

**Issue by fkamras** [michelson/Dante#101]
It looks like after selecting an image on IE11 nothing happens

**Comment by michelson** [comment]
thanks for reporting @fkamras 
I will check this when I have some time and a windows vm to try it out

**Comment by fkamras** [comment]
It might be this IE but http://stackoverflow.com/questions/27291438/ie-change-event-does-not-trigger-when-click-programmatically-on-file-input

**Comment by creativeprogramming** [comment]
IE did a lot of work implementing  _- sucking behaviors into -_  a modern browser
