### ISSUE TITLE
Formatting upon importing data

### ISSUE THREAD

**Issue by akkias** [michelson/Dante#104]
Hi Michelson,

I have been trying to replicate "Import your story" similar to https://medium.com/p/import using embedly's extract api. I am able to get data and able to put in inside 'section-inner' but I am not able to format data into dante editor format because whatever formatting happens is on paste event.

Can we have function in which we will just pass data and it will give properly formatted data.

**Comment by michelson** [comment]
I think you could try to init the editor after you put the content the
"editor" div ,  that way it should work transparently



Atte.
Miguel Michelson Martinez
www.artenlinea.com

**Comment by akkias** [comment]
Yay! it worked :)
Have a look at www.triptroop.me/import
