### ISSUE TITLE
Saving content in model

### ISSUE THREAD

**Issue by jomarbarnobal** [michelson/Dante#106]
Good day sir. 
I just want to know if this is bug ?  I am using carrierwave base64 for file upload , When saving the editor from my form it work's fine, But if i put an image below the Title, it save also the image which good thing but i cant see where it saved. 
![screencapture-localhost-3000-stories-new-1452453292373](https://cloud.githubusercontent.com/assets/12394146/12223411/cc19e6c8-b811-11e5-8c50-9380b4632d99.png)

**Comment by michelson** [comment]
Hi Jomar, 
what do you mean with "but i cant see where it saved". If you use carrierwave it will work as expected, so the image will be uploaded to the path configured in the uploader class.
In dante the upload request will respond a json with the image path 

cheers

**Comment by jomarbarnobal** [comment]
Thanks for the reply sir!
I get it now , but the image will not save if i do not put caption on image

**Comment by michelson** [comment]
Hi @jomarbarnobal , are you sure ? 
the image should be uploaded instantly. it does not require caption

**Comment by jomarbarnobal** [comment]
here's my unfinished app https://jomartestapp.herokuapp.com/   you can check it on dashboard and create new story

**Comment by michelson** [comment]
Hi @jomarbarnobal , it looks good!

I've registered into the app , and I've note that the uploads.json url does not work , when you upload something it respond a 404 status

**Comment by jomarbarnobal** [comment]
oh thanks sir ill noted that

**Comment by jomarbarnobal** [comment]
I've update my app and got a response like this " /uploads/tmp/1452545953-3-0002-4552/sotryBg.jpeg"
and i have a trouble in saving this file, can you give me a hint 
Thanks!

**Comment by michelson** [comment]
are you using a filesystem storage for uploads ? or some cdn like S3?

Atte.
Miguel Michelson Martinez
www.artenlinea.com

**Comment by jomarbarnobal** [comment]
Thanks for reply sir @michelson 
 I'm using file system storage in my app

**Comment by michelson** [comment]
Hi , in heroku context is better to use cdn like amazon s3
Dynos do not share a file system. I recommend reading How Heroku Works
<https://devcenter.heroku.com/articles/how-heroku-works>

"Changes to the filesystem on one dyno are not propagated to other dynos
and are not persisted across deploys and dyno restarts. A better and more
scalable approach is to use a shared resource such as a database or queue"

Atte.
Miguel Michelson Martinez
www.artenlinea.com

**Comment by jomarbarnobal** [comment]
Thanks sir.
I just want to test it on my local file system for learning purpose, I'm new in rails so i'm having a trouble
thanks again for the reply
