### ISSUE TITLE
Text align support?

### ISSUE THREAD

**Issue by noctivityinc** [michelson/Dante#110]
Hi-

This is amazing work, thanks for it.  Maybe I am missing it but how do I text align something, specifically center align?

**Comment by michelson** [comment]
Hi @noctivityinc , thanks

justify Center | Right | Left are not implemented features, but it could be implemented easily. Take a look at this file  https://github.com/michelson/Dante/blob/master/app/assets/javascripts/dante/menu.js.coffee

**Comment by michelson** [comment]
This will not be implemented in Dante. As is not a part of Medium's features. As I said in the previous comment this could be implemented easily as an extension.

please reopen this or create another ticket as you will if you need any help on this.
