### ISSUE TITLE
Specifying POST Params

### ISSUE THREAD

**Issue by noctivityinc** [michelson/Dante#111]
In issue #76 you asked why we would need to specify the post params.  In RoR, params are sent using the resource name.  For example, I am creating an internal blog and have the body of the post in content field.  I need to send it as a param called blog_post[content] to stay DRY.  

Given that you offer this as a Ruby 4.0 gem, I hope this make sense why we need it.

**Comment by michelson** [comment]
Hi , the best way is to use a form, before the submit event copy the editor content to some hidden text field along with other fields

**Comment by michelson** [comment]
reopen if you have more questions on this
