### ISSUE TITLE
Video embedding

### ISSUE THREAD

**Issue by flowerett** [michelson/Dante#112]
Hello,
I have a problem with video embedding on windows. Here is the details:
- browser: Google Chrome 49.0.2623.87 (latest at the moment)
- the only differences in the html embedded from Windows and MacOS:
MacOS version:
<img width="953" alt="screen shot 2016-03-09 at 11 35 42" src="https://cloud.githubusercontent.com/assets/2693127/13632672/28286e60-e5eb-11e5-882f-de366e0bfa2d.png">
Windows version (doesn't have additional elements inside **body** tag:
<img width="936" alt="screen shot 2016-03-09 at 11 37 10" src="https://cloud.githubusercontent.com/assets/2693127/13632702/514051a0-e5eb-11e5-8b2e-5dd509c24728.png">

* Could anybody else confirm this error?
* Is it `Dante` or `embed.ly` bug?
* For what this `#document` tag is used for? Is it tag at all (as I can't copy it)?
* Could anybody point me to the place where it could be fixed? I can't see any regarding code in the embed template: https://github.com/michelson/Dante/blob/master/app/assets/javascripts/dante/tooltip_widgets/embed.js.coffee#L18

Thanks in advance!

update:
latest FireFox works well both on MacOS and Windows

update:
looks like this is an http, https issue (mention the `src` attr for both pictures) as Chrome is more strict on that

**Comment by flowerett** [comment]
Ok, for now I solved it by adding additional parameter `scheme` as mention here: http://docs.embed.ly/docs/oembed

https://github.com/michelson/Dante/blob/master/app/assets/javascripts/dante/tooltip_widgets/embed.js.coffee#L45:
```javascript
$.getJSON("#{@current_editor.oembed_url}#{$(@node).text()}&scheme=https")
```
Will it be good to have an ability to pass it through option params?

**Comment by michelson** [comment]
Hi @flowerett , thanks for report this. I agree with this. 

by the way, are you using https in your site ?

**Comment by flowerett** [comment]
Hi, @michelson !
Yes. But to be precise I used https since this site is not in active development anymore :)
Could try to create a PR for this feature but not in a near future.
