### ISSUE TITLE
Image Styling

### ISSUE THREAD

**Issue by galki** [michelson/Dante#115]
On medium.com after you upload an image you can click it and a styling menu will pop up. It would be good to have something similar or even a way to customize your own.

I imagine that giving the figure/image element a css class would be good enough.

**Comment by akkias** [comment]
Thanks for adding the feature again, I have been waiting for this feature since more than year now, hope we will get update soon.

**Comment by michelson** [comment]
Hi guys,
@galki you mean the image popover to align image, right ?

**Comment by galki** [comment]
Yes that's right

2016年6月10日金曜日、Miguel Michelson Martinez<notifications@github.com>さんは書きました:

**Comment by michelson** [comment]
basic align is done, check out demo!

**Comment by galki** [comment]
Awesome! Thanks!.

Btw I just switched from medium editor + plugins and dante is better and is much easier to work with.

Btw 2: I noticed ImageTooltip.alignWide and ImageTooltip.alignFill are not implemented yet, is it coming or do we write our own?

**Comment by michelson** [comment]
Hi @galki 
Thanks for your comments on Dante. 
Yes, definitively those features will come but without an ETA yet. 
Those two features are hard because it breaks editor's markup into multiple sections, so we are going to deal with other problems besides image's pure  alignment
