### ISSUE TITLE
clean_dante_post doesn't seem to exist

### ISSUE THREAD

**Issue by netpenthe** [michelson/Dante#117]
in the readme.md it references 'clean_dante_post' but it doesn't work and i can't see it in the source anywhere.. is this meant to be a helper we write ourselves?

**Comment by michelson** [comment]
Hi @netpenthe ,
sorry for the confusion. Yes, that is an `imaginary` method to display post. In some projects I've implemented some cleaning helper methods to display the post. in others I've implemented the sanitize before the post is persisted to db. So is up to you how you handle that.

I will include a note in the README. thanks for report this.

**Comment by michelson** [comment]
I've fix the readme note, thanks for report this.

**Comment by netpenthe** [comment]
thank you!
