### ISSUE TITLE
Deleting images

### ISSUE THREAD

**Issue by galki** [michelson/Dante#119]
There should be some way of deleting images on the server.

Suggestions:

- provide a _delete_url_ option
- send a delete request to _upload_url_ url

**Comment by michelson** [comment]
This could be implemented in the image behavior, detecting when the image is removed , then you could send an ajax request to remove images. It sounds good idea.

**Comment by galki** [comment]
Okay, I made a pull request just in case.

**Comment by michelson** [comment]
v0.1.4 introduces `image_delete_callback` option
