### ISSUE TITLE
stop method

### ISSUE THREAD

**Issue by galki** [michelson/Dante#121]
I'm using dante editor on a single page app and worried about memory leaks.

Is `editor = null` good enough or should there be a `editor.stop()`?

**Comment by michelson** [comment]
Uhm , interesting. have you face some memory issues with editor ?

yes , `stop` or `destroy` could be a good idea to remove the instance and stop listening events

**Comment by galki** [comment]
I briefly checked the memory usage and there doesn't seem to be any problems.

**Comment by michelson** [comment]
good!
