### ISSUE TITLE
image css filters

### ISSUE THREAD

**Issue by galki** [michelson/Dante#122]
Not sure if surpassing medium.com is on the agenda, but these would be way cool and easy to implement too if added to the image tooltip. I'd be happy to supply the classes.

http://www.w3schools.com/cssref/css3_pr_filter.asp

**Comment by michelson** [comment]
Hi @galki, this sounds very cool feature.
I'm not sure to include this in the Core, but definitively as an extension.
As a Rule, Dante wants to be a 1-1 port of Medium so anything beyond that should be designed as an extension.

If you need help with this let me know. I will keep this issue open for now

best

**Comment by galki** [comment]
Okay. Are extensions going to be packaged together with Dante or is it something that should be done individually?

**Comment by michelson** [comment]
Yes , default extensions are packaged but you can extend with separated modules. and those could be external plugins.
You can add custom tooltip menu items (Dante.View.TooltipWidget) and add custom behaviours to operate at text interaction level. Dante.View.Behavior. so if you want to dive in deeper check wiki on custom tooltip and check out the behaviors files (image, suggest, list) and pop_over.

**Comment by galki** [comment]
Excellent, looks good, thanks!

Btw for this I was thinking extending Dante.Editor.ImageTooltip

**Comment by michelson** [comment]
yup , that sounds good, you could extend the `ImageTooltip` behavior and create a new class `ImageTooltipExtended` that inherits `ImageTooltip`, then when you configure the behaviors in dante initializer you can replace the image with the new behavior.
Let me know if you need any help
