### ISSUE TITLE
Tooltip style on Safari

### ISSUE THREAD

**Issue by n1ckbren** [michelson/Dante#143]
![screen shot 2016-10-09 at 7 41 57 pm](https://cloud.githubusercontent.com/assets/8319746/19222066/7d8b7526-8e58-11e6-93e2-833525d5d465.png)

Fix:
```
li {
  &.dante-menu-divider,
  &.dante-menu-button {
    display: block !important;
    float: left !important;
    height: 42px !important;
    line-height: 42px !important;
  }
}
```

**Comment by cristianferrarig** [comment]
Hi @n1ckbren, thanks for report this! 👍 
I think that a better solution may be this:
```
.dante-menu-button {
    vertical-align: top;
}
```
