### ISSUE TITLE
Please allow to edit caption html

### ISSUE THREAD

**Issue by creativeprogramming** [michelson/Dante#146]
The formatting tooltip is not activated while selecting  text on a caption, but I think it should, eg. to make possible to add a link (eg. to give credits to the image author website)

On medium.com that works and it allows to add link,bold formatting and private notes.

**Comment by michelson** [comment]
yes, I think we should implement that too

**Comment by creativeprogramming** [comment]
I 'hack/patch-ed' it adding this code:

  

```javascript
  Editor.prototype.handleMouseUp = function(ev) {
      var anchor_node;
      utils.log("MOUSE UP");
      anchor_node = this.getNode();
//start hack
      var n=anchor_node; if (n.tagName=="FIGURE"){n=$(parent).find("figcaption").get(0); parent=n.childNodes[0];} anchor_node=n;      
//end hack
      if (_.isNull(anchor_node)) {
        return;
      }
      this.prev_current_node = anchor_node;
      this.handleTextSelection(anchor_node);
      this.hidePlaceholder(anchor_node);
      this.markAsSelected(anchor_node);
      return this.displayTooltipAt(anchor_node);
    };
```

the same on keyup handler

**Comment by michelson** [comment]
Hey @creativeprogramming , thanks for this

would you like to submit a PR ? 
note that the source is in coffeescript , it would be nice to make this optional too.

best

**Comment by creativeprogramming** [comment]
Sure, I'll do a PR in the future, anyway now I'm in a rush with a project I'm not editing the coffee sources but hacking the builded js, but as in the future I want to be able to 'stay updated' I'll surely consolidate my changes in coffee and try to PR you as much as possible for features I'm adding.

Anyway I did a typo while writing my hack in this in git issue (I was from mobile), the real solution is:

```
//start hack
      var n = anchor_node; 
      if (n.tagName == "FIGURE") { 
             n = $(n).parent().find("figcaption").get(0);
       } 
      anchor_node = n;      
//end hack
```
