### ISSUE TITLE
Plugin system to extend Dante and create button  in pure js

### ISSUE THREAD

**Issue by creativeprogramming** [michelson/Dante#147]
Not a ruby/coffee developer. Is there a way to plug some js to extend the Dante buttons? What about a plugin system like summernote editor?

**Comment by michelson** [comment]
Hi @creativeprogramming , have you seen the wiki, check this https://github.com/michelson/Dante/wiki/Create-custom-tooltip-button

you have 3 kinds of plugins. 

tooltip widgets: (buttons for inline tooltip (+) )
popovers: (image align popover, for example)
behaviors: (to override paste for example)

best

**Comment by creativeprogramming** [comment]
Awesome, that's perfect! Thanks for pointing me the wiki, honestly i just read the readme and did't checked the wiki on github.
