### ISSUE TITLE
Please add store_failure_handler callback and so on

### ISSUE THREAD

**Issue by creativeprogramming** [michelson/Dante#148]
It will be useful to handle cases like 'session expired', server side validation failures, localStorage versioning fallback in case of missing network connectivity etc...

**Comment by michelson** [comment]
yup, check out the #136 PR, it has a enhanced save behaviour, still need to implement the callback on error, but it should be a piece of cake. I plan to merge that branch very soon as we already use it in production

**Comment by creativeprogramming** [comment]
Good, yes also the `before_xhr_handler` and other things you added in the #136 is very useful for me too,  just please remember add the error one too (or an always fired  after_xhr_handler) thanks
