### ISSUE TITLE
Error: error parsing interpolated value in Rails

### ISSUE THREAD

**Issue by Bodacious** [michelson/Dante#151]
When I try to add Dante to my rails 4 app, I see this:

```
Error: error parsing interpolated value
```

**Comment by michelson** [comment]
Hi @Bodacious , 

hard to tell , can you give more information ? that error occurs in browser or backend ?
how you are integrating Dante in the view ?

regards

**Comment by Bodacious** [comment]
Sorry, I must have submitted that comment before I was done writing it.

It's an error being raised by SASSC, which I *think* is a bit stricter than the standard SASS gem.

**Comment by michelson** [comment]
can you paste the complete error in order to identify which line is causing the exception.

**Comment by Bodacious** [comment]
I've just tried to create a fresh rails app to reproduce the problem for you, but I can't—it works fine in a new app.

**Comment by Bodacious** [comment]
I've just tried to create a fresh rails app to reproduce the problem for you, but I can't—it works fine in a new app.

It seems to be working fine now on my own app too—I have no idea why that was happening.

Yesterday it was complaining about this line: https://github.com/michelson/Dante/blob/master/app/assets/stylesheets/dante/_tooltip.scss#L83

It didn't like the interpolated string.

**Comment by Bodacious** [comment]
This issue seems to have come back 😕 

```
Error: error parsing interpolated value
        on line 83 of ../../../Code/Gems/dante-editor/app/assets/stylesheets/dante/_tooltip.scss
>>       -webkit-transition: -webkit-#{$tooltip-forward-transition}, $tooltip-def
   ----------------------------------^
```

I'm using a local version of the gem, but haven't modified it at all (yet)

**Comment by michelson** [comment]
can we close this @Bodacious ?
