### ISSUE TITLE
How can I change the header tags to use h1 and h2?

### ISSUE THREAD

**Issue by Bodacious** [michelson/Dante#152]
At the moment the editor is setting H1 header as `<h3>` HTML tags, and H2 headers as `<h4>`. Can I change this manually? I'd like to use `<h1>` and `<h2>` in my HTML for SEO reasons.

**Comment by michelson** [comment]
this should be configurable , sorry fot that, 
again as in #154 , you need to see the menu.coffe , and tweak it. https://github.com/michelson/Dante/blob/master/app/assets/javascripts/dante/menu.js.coffee#L32

it would be great to see a PR of this which enable this kind of configurations on the Editor.

best
