### ISSUE TITLE
How can I highlight code blocks in my article?

### ISSUE THREAD

**Issue by Bodacious** [michelson/Dante#154]
According to the [Demo](http://michelson.github.io/Dante/) Dante supports code blocks. But even on the demo, the code tool is not available in the toolbar. 

My first problem was: **How do I get the code tool to show up in the toolbar?**

I’ve “fixed” this by forking the repo, and modifying the code like so: https://github.com/KatanaCode/Dante/commit/79ae1b73efcdd75bc22cb4f4574d84b320192862

But even then, this doesn’t show the `<pre>` code blocks very well, as it breaks them into multiple `<pre>` sections when there should only be one.

How can I get the `<pre>` code blocks to format correctly?

**Comment by michelson** [comment]
Hi @Bodacious , you might need to read the source code of Dante, and hack a bit :dagger: 
look at menu.js.coffee file, all the logic you need is on that file. I think you only need to add an extra button on menu which inserts the `code` tag. that should be "configurable" but is not, sorry about that.

for the second problem , I would say that could be a problem in the logic of `handleKeyDown`, specifically in ENTER key handler , you can see how it handles it here 
https://github.com/michelson/Dante/blob/master/app/assets/javascripts/dante/editor.js.coffee#L601

let me know how it goes, I will glad to help

best!
