### ISSUE TITLE
Deleting images? (UX question)

### ISSUE THREAD

**Issue by creativeprogramming** [michelson/Dante#155]
Hi, am I wrong or to delete an image in dante the only way is to select it with a mouse hold-move like if it was a text?

Many of my test users found this not intuitive...

Is there a way to delete images with a simple click sequence? (e.g. 'click to select image' -> 'press del or canc' OR 'a popover button to delete')

**Comment by michelson** [comment]
Hi Stefano ,

It should delete images on click Del,
does not work for you ?

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by creativeprogramming** [comment]
No, click+del is not working for me, It's the most intuitive way I tried and my users too... but now I've a suspect, we use italian keyboard, maybe the keycode is different? I'll do some test/debug and update you

**Comment by creativeprogramming** [comment]
No, I was wrong there is no bug, it was due to a my customization, I deleted the 'aspectRatioPlaceholder' from the img figure wrapper so it never got the is-selected class as we've listeners set by:

```
Image.prototype.events = {
      "click .graf--figure .aspectRatioPlaceholder": "handleGrafFigureSelectImg",
      "click .graf--figure figcaption": "handleGrafFigureSelectCaption",
      "keyup .graf--figure figcaption": "handleGrafCaptionTyping",
      "mouseover .graf--figure.graf--iframe": "handleGrafFigureSelectIframe",
      "mouseleave .graf--figure.graf--iframe": "handleGrafFigureUnSelectIframe"
 };
```

anyway as i need this class stripped I added this selector to the event listener:
 
```
Image.prototype.events = {
      "click .graf--figure img": "handleGrafFigureSelectImg", //<---
      "click .graf--figure .aspectRatioPlaceholder": "handleGrafFigureSelectImg",
      "click .graf--figure figcaption": "handleGrafFigureSelectCaption",
      "keyup .graf--figure figcaption": "handleGrafCaptionTyping",
      "mouseover .graf--figure.graf--iframe": "handleGrafFigureSelectIframe",
      "mouseleave .graf--figure.graf--iframe": "handleGrafFigureUnSelectIframe"
 };
```

**Comment by creativeprogramming** [comment]
Thanks for your answer anyway I helped me :)
