### ISSUE TITLE
Dante 2 , a complete rewrite

### ISSUE THREAD

**Issue by michelson** [michelson/Dante#157]
Hi Guys, in the latest weeks we were working in a complete rewrite of Dante editor!
We are going to release it very soon, we're just testing out in our own production application to battle test it before public release. 
The interesting thing about this rewrite is that is built on top of Facebook's Draft-Js, it has a pluggable architecture where custom blocks (like video , embed , image) and tooltips (add button , link, popover) are just react components. Also this rewrite tries to follow the same principles of Dante in terms of features and visual presentation.

if you can do a quick test drive an tell us what you think we will be eternally grateful 👍 

a demo can be seen at https://michelson.github.io/dante2/ 

have a good weekend
best!

**Comment by Bodacious** [comment]
Hi @michelson 

This is great news.

The link to the Dante2 license is not working. Can you please fix it or post more info here on the new license?

Thanks

**Comment by michelson** [comment]
Hi Gavin , this is the link to the license
https://michelson.github.io/dante2/license.html

we are doing the final tweaks to the code before release

cheers

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by Bodacious** [comment]
Just purchased a license.

Please let me know when I can try it out in my application? 😄

**Comment by michelson** [comment]
Hi Gavin,
we haven't opened the repo already but we've added you as a collaborator
for you to download source

thanks for your payment!!

this is the link to accept access to repo is:
https://github.com/michelson/dante2/invitations

best regards

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by michelson** [comment]
Guys, Dante2 is out! check it out at: https://github.com/michelson/dante2
