### ISSUE TITLE
Unable to write text after giving caption to image - Firefox issue

### ISSUE THREAD

**Issue by amitpatelx** [michelson/Dante#158]
Step to reproduce.

1. Enter a caption below an image and hit enter
2. You will see the + control and a cursor blinking beside it. Now start typing.

**Actual**
No character appear on cursor position.

**Expected**
Can write text on cursor position

![selection_838](https://cloud.githubusercontent.com/assets/1289894/21719587/89834d36-d444-11e6-95f6-55e4a356ab11.png)

**Comment by dsslimshaddy** [comment]
use dante2 its released
