### ISSUE TITLE
Image upload with Multer (Nodejs)

### ISSUE THREAD

**Issue by LotharVM** [michelson/Dante#159]
Hi,

I'm using Dante editor in a NodeJS application and I'm trying to set up the image upload with [Multer](https://github.com/expressjs/multer). I've set the 'upload_url' to `/blog/upload` and when I return a img URL with `res.send ('<url>') `the editor's switches the imgsrc; that part is working fine.

The part that I can't figure out is how to save the image on my server (local for now, S3 is the next step), and pass the URL to a variable to send back. I've checked the Upload.php example and lots of Multer examples (including some already working image uploads in my app) but I still can't see how to make it work with Dante.  

Any help would be highly appreciated! 😊

**Comment by michelson** [comment]
uhm, I'm affraid I can't help much in backend specifics, but from multer repo:

> In an average web app, only dest might be required, and configured as shown in the following example.
> 
> var upload = multer({ dest: 'uploads/' })

question: when your server responds the uploaded url , how it is constructed? it's something like http://localhost:8080/uploads/thefile.jpg ?

I will try to build soon a node example for the community 😃

**Comment by michelson** [comment]
maybe you could check Dante2, it has more features and is more mantained 👍

**Comment by LotharVM** [comment]
> question: when your server responds the uploaded url , how it is constructed? it's something like http://localhost:8080/uploads/thefile.jpg ?

Yes, as the uploading part didn't work I tested the response with a random image URL from internet.

The error I get when using Multer is `Error: Unexpected field`. I think this is because I cannot name the `<form>` wrapper around the `<input>` and therefore Multer cannot communicate with it. In Dante.js I can only name the `<input>` field..  Or am I missing something?

> I will try to build soon a node example for the community 😃

That would be really really great 😃. Also, I'll check Dante2. The only thing that's scares me a little bit is the filesize; Dante2's dante-vendors.min.js is already 465kb..

**Comment by LotharVM** [comment]
I got it working with Multer now @michelson !

Had to change `upload.fields(...)` to `upload.single(...)`. The photos are now uploaded to the /uploads folder. The only thing that's left for me to fix/optimize is the response URL. It's returning the correct URL back and Dante switches the imgsrc correctly to the new one, but it's too fast.. It's not waiting for the file to be uploaded but instantly returns the new URL, so most of the time the editor show a broken image link.. When reading the Readme I see that there's an option to set a 'default_loading_placeholder', so there must be way Dante is checking for the image being uploaded, is that correct?
