### ISSUE TITLE
Image overlaps on text when aligned left

### ISSUE THREAD

**Issue by amitpatelx** [michelson/Dante#160]
![selection_034](https://cloud.githubusercontent.com/assets/1289894/23623726/19676c36-02c9-11e7-9053-68fa2fde03e7.png)

**Comment by michelson** [comment]
Hi @Amit 
yup , it seems to be a bug in the css style of the image, but you can add some breaklines (with ENTER) to avoid the overlapping.
Also you definitively could check [Dante2](https://github.com/michelson/dante2), which is a better alternative. And supports the same features of this library. Also is continuously maintaned.

cheers
