### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by rickghome** [michelson/Dante#162]
Trying to use dante on dynamically loaded pages. No problem with other libs, but dante throws a console error: Uncaught ReferenceError: _ is not defined.  I've tried multiple methods to initialize the editor after page load to no avail. Hints?

**Comment by michelson** [comment]
Try including underscore.js library

By the way , you can use dante2 , which is an improved Dante rewritten in
draft.js and react

Best

**Comment by rickghome** [comment]
That solves it, thanks for quick response. I'll give dante2 too.
