### ISSUE TITLE
image upload problem / error propagation

### ISSUE THREAD

**Issue by gbu-censhare** [michelson/Dante#164]
Hi,

We have our own servlet, which handle the image uploads,
which could be occasion throw an error,

i can see that the image handler handles the error, but the image tag is nethertheless updated in the json, and the error is not rendered in the frontend (instead the image is still shown), is this on purpose? 

i've seen you can add an upload_error_callback, can i update the frontend here?

Best,
Georg

**Comment by programmermarvin** [comment]
j m,  lkmlkm
#djdsjkk
