### ISSUE TITLE
Multer Showing Up Uploaded Image

### ISSUE THREAD

**Issue by Alpgul02** [michelson/Dante#168]
I am using multer to uplaod images. I can upload them to my database with extension. Everything look perfect but I cannot see them on my webpage.

Also note that my project needs specific images for every different articles that means in every article images changes.

**This is my article.js relevant codes:**
```
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'public/uploads')
  },
  filename: function (req, file, cb) {
    cb(null, file.originalname)
  }
})
const upload = multer({storage: storage})


// Add Submit POST Route
router.post('/add',upload.single('img'),  function(req, res){

  req.checkBody('title','Title is required').notEmpty();
  //req.checkBody('author','Author is required').notEmpty();
  req.checkBody('body','Body is required').notEmpty();

  // Get Errors
  let errors = req.validationErrors();

  if(errors){
    res.render('add_article', {
      title:'Add Article',
      errors:errors
    });
  } else {
var article = new Article({
    title: req.body.title,
    author: req.user._id,
    img:  `uploads/${req.file.filename}`,
    body: req.body.body,
   });

    article.save(function(err){
      if(err){
        console.log(err);
        return;
      } else {
        res.render('add_article', {
        });
      }
```

**And:**

```
// Get Single Article
router.get('/:id', function(req, res){

  Article.findById(req.params.id, function(err, article){
    //User.findById(article.author, function(err, user){
      res.render('article', {
        article:article,
        //imagePath: article.img,
        //author: user.name
      });
    });
  });
```

**This is my article.pug: extends layout**
```
extends layout

block content
  br
  //h5 Written by #{author}
  h1= article.title
  p= article.body
  img.img-responsive(src=article.img, alt=article.img)

  hr
  if user
    if user.id ==article.author
      a.btn.btn-default(href='/articles/edit/'+article._id) Edit 
      a.btn.btn-danger.delete-article(href='#',data-id=article._id) Delete
```

What I meant is: I can upload images to my MongoDB database but I cannot see the images in my webpage. 

This is my console.log(article.img): uploads/image.jpeg

But still I cannot understand why I cannot see them. Every answer will be apreciated.

**Comment by michelson** [comment]
The editor has to be able to get the image url when you upload it through
the editor.

In your example I don't see any dante editor related code

**Comment by Alpgul02** [comment]
> The editor has to be able to get the image url when you upload it through the editor. In your example I don't see any dante editor related code El sáb., 9 de mayo de 2020 3:28 p. m., Alpgul02 <notifications@github.com> escribió:
> […](#)

In my website there will be no image url because in my article page all title, author, body and img are found. So that we dont need to open a new img url because our images will be uploaded to my article page.

**Comment by Alpgul02** [comment]
So you mean that firstly I have to make a uploaded image url then implement that url just like this:
...src="localhost/uploaded/image.png"
Do you mean this or not ?

**Comment by michelson** [comment]
Hi , I can't help you out with your backend integration. I will suggest you use Dante2 https://github.com/michelson/dante2 , because I'm not supporting Dante1 anymore

**Comment by Alpgul02** [comment]
It is solved
