### ISSUE TITLE
Not able to add DanteEditor to a function component

### ISSUE THREAD

**Issue by bobber205** [michelson/Dante#175]
I think this editor looks amazing.

I have a project that uses only functional components and ReactHooks. (not sure if related but adding just in case)

Here's what I'm doing

```js
import DanteEditor from 'dante3';
````

```jsx
return (
<DanteEditor
                content={'hello world'}
            />
)
```

I'm getting this once the app refreshes.

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

Any idea on what's causing this?

![image](https://user-images.githubusercontent.com/5841107/119566354-e6ffd200-bd5f-11eb-8de0-1ebf13ee12d3.png)

Thanks!

**Comment by michelson** [comment]
Hi there, please check this codesandbox https://codesandbox.io/s/dante3-editor-example-gh9hu , it's working with function components 
I hope it helps 👍
