### ISSUE TITLE
Dante3 Ordered list doesn't work properly

### ISSUE THREAD

**Issue by DarkPonyBee** [michelson/Dante#177]
Hi @michelson .
Thanks for creating Dante3 editor.

Dante3 editor ordered list doesn't works properly.
It works exactly same as the unordered list.

![image](https://user-images.githubusercontent.com/68030494/120212382-ed7ac780-c1ff-11eb-97b0-15b16986e1ff.png)

**Comment by michelson** [comment]
done  , example at https://codesandbox.io/s/dante3-editor-example-gh9hu

thanks for reporting

**Comment by DarkPonyBee** [comment]
Thanks @michelson .
I tried to add images from example project, but it triggers error.
![image](https://user-images.githubusercontent.com/68030494/120412665-f1ecd080-c324-11eb-82c8-22165831bb10.png)
