### ISSUE TITLE
Feature request: sort images among praragraphs

### ISSUE THREAD

**Issue by hassan-jahan** [michelson/Dante#19]
Excellent work! 

I think it would be great if it was possible to drag and drop images (or maybe other blocks) among paragraphs like what is in http://orthes.github.io/medium-editor-insert-plugin/

**Comment by michelson** [comment]
Hi @cyberiaa :+1: to this request

**Comment by nolotus** [comment]
best with  
![image](https://cloud.githubusercontent.com/assets/7419087/14063855/f32f816c-f418-11e5-8a6c-2ac0edc7dbb5.png)
