### ISSUE TITLE
Missing RTL Support When Migarate To Dante 3 

### ISSUE THREAD

**Issue by pooooriya** [michelson/Dante#191]
hi ever one , dante 2 has built in support for rtl support but dante 3 doesnt have rtl support with css cant do the same stuff 
please help me ! thanks

**Comment by michelson** [comment]
you should be able to do this with CSS; the browser will handle this natively

**Comment by pooooriya** [comment]
no is not support it , dante 2 has supported but dante 3 is not
if want to change direction base on first char

**Comment by pooooriya** [comment]
how can find the code that you used for change direction base on first char and then added to dante 3  ?  I Search for it in dante 2 but i cant found it

**Comment by pooooriya** [comment]
I searched for it but I Found All Of The Core Base Of Editor Uses Tiptap and Now I have To change defaults of tiptap , maybe it has a specefic plugin to do this stuff but I cant found it

**Comment by pooooriya** [comment]
I Finally Found Add dir="auto" to parent element , thanks for helping and this cool package  :)

**Comment by michelson** [comment]
glad you solved it, I guess the CSS rule `direction: rtl;` will do the trick too.

cheers
