### ISSUE TITLE
la opcion de multicolor no desaparece

### ISSUE THREAD

**Issue by bluezin** [michelson/Dante#195]
Cuando le doy click a la opcion de colores y intento darle otro click para q desaparesca, no lo hace :''(

**Comment by michelson** [comment]
Hola Yadira, estás usando Dante2 o Dante3 ?

**Comment by bluezin** [comment]
Hola estoy usando Dante 2 
![image](https://user-images.githubusercontent.com/49109063/132780068-72cb6faf-dd3a-4c1c-90ae-97a3901fce3c.png)

**Comment by bluezin** [comment]
quizas me este faltando algo pero no se 
![image](https://user-images.githubusercontent.com/49109063/132780328-fdb947be-56f7-4f5b-9d26-ffe84e79c032.png)

**Comment by bluezin** [comment]
vi que tambien se le agrega  una opcion **handleReturn**, podra ser eso ?, yo no lo estoy pasando ese prop

**Comment by michelson** [comment]
al parecer encontraste un bug :) 
hice un fix a esto, puedes probar la version Dante2-0.5.3-alpha.7 
espero funcione

**Comment by bluezin** [comment]
vale, entonces, no es porque me falto agregarle un hanldeReturn verdad?

**Comment by bluezin** [comment]
"Dante2": "0.5.3-alpha.6", ahorita estoy usando esta version

**Comment by bluezin** [comment]
Esto no podria solucionarce sin actualizar la version?, :(

**Comment by michelson** [comment]
acabo de publicar la versión Dante2-0.5.3-alpha.7 con el fix

**Comment by bluezin** [comment]
super!, gracias :)

**Comment by bluezin** [comment]
se soluciono gracias!!!!!!!!!!!!
