### ISSUE TITLE
Hola, tengo una pregunta , como podria hacer para que el loading de la imagen avance ? , estuve buscando pero no encuentro una respuesta :(, estoy usando Dante 2

### ISSUE THREAD

**Issue by bluezin** [michelson/Dante#197]
<img width="652" alt="Screen Shot 2021-09-16 at 3 18 16 PM" src="https://user-images.githubusercontent.com/49109063/133680297-ca853d9b-5d3d-4b62-bf8e-0feb9a3f30ee.png">

**Comment by michelson** [comment]
hola, 
mira `updateProgressBar` en el componente image.js en components/blocks de Dante2

**Comment by bluezin** [comment]
super, gracias

**Comment by bluezin** [comment]
No logro solucionarlo :( , lo tengo igual 
<img width="756" alt="Screen Shot 2021-09-16 at 7 39 16 PM" src="https://user-images.githubusercontent.com/49109063/133705910-e083c44f-c669-4f40-95e5-58db190639af.png">

y en los props le estoy pasando 
    
<img width="721" alt="Screen Shot 2021-09-16 at 7 44 46 PM" src="https://user-images.githubusercontent.com/49109063/133706307-e20146e9-cb73-4881-b789-c479b361befc.png">

**Comment by bluezin** [comment]
intente pasarle en los props del upload_url con un string, pero  me lanzo un error
