### ISSUE TITLE
react version mismatch error and an invalid hook call at menubar

### ISSUE THREAD

**Issue by buddy18** [michelson/Dante#217]
I was trying to use the dante3 library.  I got react version mismatch error and an invalid hook call at menubar. can u help me out?
@michelson 
![Error](https://user-images.githubusercontent.com/32009167/158112818-8bc00e17-8a9e-4f4e-af1e-2c89969223f3.png)

**Comment by michelson** [comment]
can you send a reproducible example?

**Comment by buddy18** [comment]
![code1](https://user-images.githubusercontent.com/32009167/158305274-26c1bd88-e9a0-4274-9518-dc7c4ed10c42.png)
![code2](https://user-images.githubusercontent.com/32009167/158305282-704261ef-9a4c-4890-b22d-10e4112e8810.png)

**Comment by michelson** [comment]
can you send a reproducible example?
