### ISSUE TITLE
How to multi-column?

### ISSUE THREAD

**Issue by artknight** [michelson/Dante#230]
I love what you have created! I would like to know if there is a way to add a multi column layout, ...similar on how a media file an be left aligned.

<img width="234" alt="Screen Shot 2022-06-10 at 11 17 33 AM" src="https://user-images.githubusercontent.com/157762/173097240-b01476ed-9f19-4d1f-a86b-988dcf150f7e.png">

Ideally I would love to have option to add a two or three column layout.

Thank you in advance!
Art

**Comment by michelson** [comment]
Hello Art, At the moment that is not possible for text

**Comment by artknight** [comment]
@michelson any plans to implement it in the future?

**Comment by artknight** [comment]
@michelson also, I have an application that runs on vanillaJS. I would like to implement your editor there. Is there a vanillaJS script I could include?

**Comment by artknight** [comment]
answered
