### ISSUE TITLE
prosemirror-state package constructor issue

### ISSUE THREAD

**Issue by SolutionArchitectMert** [michelson/Dante#233]
With a normal usage of dante3, application throw below exception. Based on my research, there is a new update for prosemirror-state package but dante is not aware of this update. So, it throw below exception.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/109334825/179274847-18645d49-1f97-4ec0-8c10-31e4367f4416.png">

**Comment by michelson** [comment]
can you help with a PR?

**Comment by michelson** [comment]
I've updated the dependences in version 1.1.4, it's working now.
Please reopen if you find issues on this regard
