### ISSUE TITLE
"Cannot load such file -- coffee_script" for Rails 7

### ISSUE THREAD

**Issue by Bishwas-py** [michelson/Dante#238]
I am trying to install Dante Rails on our open-source Rails app called [Deviser Club](https://github.com/Bishwas-py/deviser-club). The web app is currently using custom-made TipTap editor with Stimulus JS.

I got this issue while booting the edit page. 

```
LoadError in PostsController#edit
cannot load such file -- coffee_script
```

`manifest.js`

```
// changing the editor
//= require 'dante'
//= require sanitize
//= require underscore
```

`Gemfile`
```

gem "dante-editor"
gem 'underscore-rails'
gem 'rails-sanitize-js'
```

`application.scss`
```
@import "dante";
```

`views/posts/edit.html.erb`
```
    <div id="editor editable" >
      <%= @post.body %>
    </div>
```
Also, I wanna know how can we get the text value from the editor to our rails app.

**Comment by michelson** [comment]
check this example: https://gist.github.com/michelson/5d124fa4df0d06e44eb80c414344728c
reopen if you find issues
