### ISSUE TITLE
cannot build dante3

### ISSUE THREAD

**Issue by artknight** [michelson/Dante#241]
Hi,
I am trying to build dante3 but I keep on getting an error.

I am running `npm run dante3_build`

output: 
```
dante3: [!] Error: Package subpath './package.json' is not defined by "exports" in /Users/max/Downloads/experiments/dante/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json
```

any ideas?

**Comment by michelson** [comment]
no idea, sorry.

**Comment by artknight** [comment]
@michelson ok, seems I was trying to build inside /packages/dante3 instead of root. That is working now.

Do you think you could create a separate clean repo just for dante 3? This seems unnecessarily messy :(
