### ISSUE TITLE
running Dante locally with errors...

### ISSUE THREAD

**Issue by artknight** [michelson/Dante#247]
So, I just forked the repo and installed/ built the code 
1. `yarn install`
2. `yarn dante3_build`
3. `yarn dev`

The site runs on :3001 just fine. When I tried to play with it I am seeing a bunch of errors in the console
<img width="1522" alt="Screen Shot 2022-08-24 at 6 12 34 PM" src="https://user-images.githubusercontent.com/157762/186532785-06b44956-7d7d-4b39-8f9c-28acfab70b1b.png">

I went to https://www.dante-editor.dev/ and I NOT seeing the errors. 

If my local build is faulty.. would you please let me know what to run to get it fixed?

Thanks!

**Comment by michelson** [comment]
yes, those are warnings (not errors) and are visible only on dev environment
