### ISSUE TITLE
where can I find "Clear Format" ?

### ISSUE THREAD

**Issue by artknight** [michelson/Dante#248]
I have looked around I cannot figure out how to remove any formatting. The only way that I see if the `cmd + z` to undo the action. 

However, where can find an option to `clear format`?

**Comment by michelson** [comment]
maybe you could start looking here: https://github.com/ueberdosis/tiptap/issues/101

**Comment by michelson** [comment]
editor.commands.clearContent(true);

**Comment by reorx** [comment]
`editor.chain().focus().unsetAllMarks().run()`
