### ISSUE TITLE
New button example?

### ISSUE THREAD

**Issue by Charuru** [michelson/Dante#25]
How do I add simple new features? For instance I want to add a span 'highlight' class to a selection?

**Comment by michelson** [comment]
Hi @Charuru , there is no an straight way to do it right now , 
But I think you could hack on Dante.Editor.Menu . or Dante.Editor, since they are like a Backbone.View so they accepts events and you could override some functions or listen for new events.

Best!

**Comment by michelson** [comment]
for new buttons , check this wiki page https://github.com/michelson/Dante/wiki/Create-custom-tooltip-button
also you can extend Dante.editor in order to override the default behavior , it seems to be a good idea to add callbacks for some actions in next releases.
