### ISSUE TITLE
prosemirrorState.PluginKey is not a constructor

### ISSUE THREAD

**Issue by MuhammadAzamat** [michelson/Dante#251]
Hi, @michelson 
I'm getting this error : "Uncaught TypeError: prosemirrorState.PluginKey is not a constructor"

![image](https://user-images.githubusercontent.com/99191056/198022442-6917872f-0959-4646-ae38-77eda503bd9d.png)

Could You provide to solve problem?

**Comment by michelson** [comment]
not sure what the problem is , if you can add a codesandbox to replicate the error will help

**Comment by MuhammadAzamat** [comment]
Is there any restrictions on using dante3, on nextjs, or with typescript, or other ?
I'm using react 18 without typescript

**Comment by vincent0426** [comment]
same problem

**Comment by michelson** [comment]
not sure what the problem is , if you can add a codesandbox to replicate the error will help.

**Comment by mb-1208** [comment]
same problem here :/

**Comment by michelson** [comment]
Hi I think we have solved the issue in the latest version. please reopen this if you need more help
