### ISSUE TITLE
RangeError: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by akashic-rb** [michelson/Dante#268]
I got this issue 
<img width="413" alt="Screenshot 2023-02-09 at 2 29 42 PM" src="https://user-images.githubusercontent.com/51085670/217746285-dd0ef54d-6211-4d35-9c9b-07e45ac61b70.png">
just by adding these line
```js
<Dante3Editor
      content={content}
      onUpdate={(editor) => console.log(editor))}
 /> 
```
It was crashing my app (total blank page) and I edited some in my code then it rerendered the editor perfectly fine
It just seems to crash the first time load the app, but still frustrating

**Comment by marvoh** [comment]
I have the same problem using both @akashic-rb  and example [here](https://codesandbox.io/s/dante3-editor-example-gh9hu?file=/src/App.js:1061-1159)

**Comment by michelson** [comment]
can you provide the failing example?  codesandbox?, your node version  etc...

**Comment by marvoh** [comment]
I have a re-useable component called rte.jsx This is how it looks like:

```
import * as React from "react";
import Dante from "dante3";

export const RichEditor = () => {
  return <Dante />;
};
```

I use is in other functional components as follows:

```
import { RichEditor } from "components/forms/rte";

export const ContentContainer = ({}) => {
<RichEditor />
}
```

I did a clean install again on a fresh branch before creating sandbox, I got this error now.

![image](https://user-images.githubusercontent.com/5451142/223772160-de416da6-e06f-4796-bcf5-22ad01705c8a.png)


Here are my dependencies: 

```
"dependencies": {
    "@fluentui/react": "^8.20.0",
    "@fluentui/react-components": "^9.0.0-beta.3",
    "@fluentui/react-hooks": "^8.3.7",
    "@fluentui/react-icons-mdl2": "^1.2.8",
    "@fluentui/react-northstar": "0.65.0",
    "@fluentui/theme-samples": "^8.1.26",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@tiptap/pm": "^2.0.0-beta.220",
    "d3": "^3.5.17",
    "dante3": "^1.1.6",
    "fast-deep-equal": "^3.1.3",
    "gh-pages": "^3.2.2",
    "react": "^18.0.2",
    "react-dom": "^18.0.2",
    "react-hook-form": "^7.9.0",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-use": "^17.2.4",
    "redux-saga": "^1.1.3"
  },
```

**Comment by michelson** [comment]
Hi I think we have solved the issue in the latest version. please reopen this if you need more help
