### ISSUE TITLE
Seems to be impossible to delete embeds

### ISSUE THREAD

**Issue by PedroEsperanca** [michelson/Dante#27]
sorry for bugging you guys so much :p 
I just really want to use this editor :)

**Comment by Casao** [comment]
Just was able to delete an embedded youtube and twitter by backspacing.

**Comment by PedroEsperanca** [comment]
try with the other embed (not the video).
Both backspace and delete get the cursor into the 'box' and start deleting stuff there

**Comment by PedroEsperanca** [comment]
the video does work well with backspace, but not with delete

**Comment by michelson** [comment]
Hi @PedroEsperanca , you are right the link embeds seems to not be deletable , 
are you using windows or mac keyboard ?

**Comment by michelson** [comment]
Another issue is that when you press backspace on captions for images or videos , the embeds is deleted.
I think this behavior have some problems that need to be fixed right away , 
please hang on :)
another issue is that when you press backspace on captions for images or videos , the embeds is deleted.
This behavior in particular have some problems that need to be fixed right away , 
please hang on :)

thanks for reporting @PedroEsperanca !

**Comment by michelson** [comment]
Hi @PedroEsperanca , 
I've a working branch which handles this issue.
you can check it out here https://github.com/michelson/Dante/tree/0.0.7-fixes 

### features: 

+ link embed are deleted when all text is erased
+ backspace on caption for image/embeds doesn't remove the entire embed
+ when backspace on selected emebed it will remove the embed propperly

tell me if it works for you to merge it

Best!

**Comment by PedroEsperanca** [comment]
awesome! I'll try it out in the morning :D

**Comment by PedroEsperanca** [comment]
oh.. windows 8.1

**Comment by PedroEsperanca** [comment]
The new features work :)

May I suggest some other enhancements? Maybe some are easy.

- video placeholder could be: "Type caption for embed (optional)"
- when captions become empty the placeholder should re appear (this also solves the problem that currently it's not possible to click on an empty caption and start editing it immediately) 
- clicking enter on selected embeds or images could create a new line

**Comment by michelson** [comment]
Hi @PedroEsperanca , we release 0.0.8 with the fixes, 
the last 2 points you mention are postponed for the next release. 
I'll close this and port these two points as separate issues since they are not related with embed close.

Best!

cheers!

**Comment by PedroEsperanca** [comment]
oh cool! Thanks for mentioning me in the release :D
