### ISSUE TITLE
Dante 3 Nextjs page to Nextjs app

### ISSUE THREAD

**Issue by HaToan** [michelson/Dante#273]
I try to add Dante3 Editor to nextjs project but error and I don't know why, someone help me please

![image](https://github.com/michelson/Dante/assets/10083309/db6abc77-f739-4ac6-b011-0cb1bf91ff79)

**Comment by HaToan** [comment]
nothing

**Comment by vigneshrams** [comment]
@HaToan Were you able to get it up and running? I am trying to ass dante 3 in NextJS 13

**Comment by HaToan** [comment]
I waited a bit too long and I switched to lexical.Thank you

Vào Th 4, 18 thg 10, 2023 vào lúc 17:41 vigneshrams <
***@***.***> đã viết:

**Comment by michelson** [comment]
Hi there, note that this editor is into a nextjs app with version 13. I also did point out examples that are available on codesandbox, it also works on the main site, and I have this working on several sites that I run on production. Not sure what else you expect.

Good luck with Lexical anyway ✌️.

**Comment by vigneshrams** [comment]
@michelson Got the link to codesandbox [https://codesandbox.io/u/michelson](https://codesandbox.io/u/michelson). Just wanted to know, 
1. How to upload images to my server when images are selected?
2. Can I customize the tooltip that appears from the + icon - Like disable voice and video recorder?
3.  How do I stop deleting images by clicking enter in Image Caption?

I am learning to build a blogging platform on my own. Please help me with this.

**Comment by michelson** [comment]
Check the examples, and navigate the code. the plugins have components with callbacks that let you grab the uploaded file.

**Comment by vigneshrams** [comment]
Thanks @michelson . I am using this example as reference [https://codesandbox.io/s/dante3-example-krc4r?file=/src/App.js](https://codesandbox.io/s/dante3-example-krc4r) to upload Image to server.
I am able to disable voice and video recorders also.  
Just want to find out how to stop deleting Images when enter is hit on the Image caption.

Thanks a lot.
