### ISSUE TITLE
Dante3 doesn't work with Vite

### ISSUE THREAD

**Issue by cabello** [michelson/Dante#274]
Hi there 👋 

I hope you are doing great.

Follow up of #257 that is closed and from Dec 2022 so likely stale.

**Problem:** Dante3 doesn't work when using Vite.

**How to reproduce**

Add dante3 to any vite application, for example:

If I `yarn add dante3` while using vite and try to put an `DanteEditor` anywhere in the app, I get the following errors when booting up the server:

```
  ➜  Local:   https://localhost:5173/
  ➜  Network: https://192.168.2.12:5173/
  ➜  press h to show help
✘ [ERROR] Could not resolve "@emotion/styled"

    ../node_modules/dante3/package/umd/Dante.js:2:442:
      2 │ ...s'), require('@tiptap/extension-link'), require('@emotion/styled'), require('polished'), require('react-colorful'...
        ╵                                                    ~~~~~~~~~~~~~~~~~

  You can mark the path "@emotion/styled" as external to exclude it from the bundle, which will
  remove this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@emotion/react"

    ../node_modules/dante3/package/umd/Dante.js:2:615:
      2 │ ...axios'), require('medium-zoom'), require('prop-types'), require('use-countdown-timer'), require('@emotion/react')) :
        ╵                                                                                                    ~~~~~~~~~~~~~~~~

  You can mark the path "@emotion/react" as external to exclude it from the bundle, which will
  remove this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.
```

Then I found the peer dependencies in the source of the `package.json`: https://github.com/michelson/Dante/blob/8fc7d2e74cc6811f9190a2a3d29dbf752aea94f9/packages/dante3/package.json#L76C1-L76C1

And this is after adding `@emotion/react` and `@emotion/styled` as dependencies:
```
Dante.js:1117 Uncaught TypeError: styled.div is not a function
    at Dante.js:1117:32
    at Dante.js:2:66
    at ../node_modules/dante3/package/umd/Dante.js (Dante.js:5:1)
    at __require (chunk-ROME4SDB.js?v=79b2f954:11:50)
    at Dante.js:4240:3
```

I tried a few other tricks like:  https://dev.to/glocore/configure-emotion-with-your-vite-react-project-7jl

But I could not make it work with my current setup.

Cheers 💜

**Comment by michelson** [comment]
not sure; version 1.2.8 of dante3 works on all of our projects.

Try to add these versions of dependencies:

    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@headlessui/react": "^1.5.0",
