### ISSUE TITLE
Hi the code is not working in next js , what can I do? 

### ISSUE THREAD

**Issue by no-naame** [michelson/Dante#277]

**Comment by michelson** [comment]
Hi, look at the repository repo site. The public site actually uses NextJS. We needed to add some required stuff as NextJS does not accept ES modules. 

https://nextjs.org/docs/messages/import-esm-externals

this is me assuming the error, as this issue provided here has no log trace or exceptions given. Closing this now

**Comment by no-naame** [comment]
Hi , Thankyou for replying ,I removed require from the code and used import, It was not working even then , it was showing lots of problems
