### ISSUE TITLE
Can't paste image 

### ISSUE THREAD

**Issue by thangngoc89** [michelson/Dante#33]
I use your demo page to test this function but It seems pasted image doesn't work at all. (I can confirm about image in my clipboard, I with the same condition, I pasted it into http://try.discourse.org, It worked well)
- Chrome  40.0.2214.91 m
- Windows 8.1

**Comment by michelson** [comment]
Hi @thangngoc89 thanks for reporting this.
pasted images works but in some cases the copied html has the images into a <figure> element or any element that is not permitted or sanitized.
In the next days I will fix this behavior

best!

**Comment by dandv** [comment]
Same problem here. I'm updating

* http://socialcompare.com/en/comparison/javascript-online-rich-text-editors
* https://github.com/cheeaun/mooeditable/wiki/Javascript-WYSIWYG-editors
