### ISSUE TITLE
Manually post the content?

### ISSUE THREAD

**Issue by thangngoc89** [michelson/Dante#35]
I'm planing to use your awesome editor in my project but on the post page, there are some forms need to be filled before send to server (there is also a real-time data saving).
So I hope there will be an option to turn off Dante's auto post, let me serialize the content and send it manually.
By the way, when using Dante's or any Medium clone editor. I'll be tied into the editor (In my developing app, I currently using Medium-Editor with jQuery plugin to embed contents and images. Dante can't show the image in the post). So a markdown option would to awesome on the roadmap.

**Comment by michelson** [comment]
Hi @thangngoc89 , thanks for your feedback
1. by default Dante will not save the content , just leave the *store_url:* option blank.

2. In my apps I tend to override the submit behavior and copy the value of Dante to the input field of the form,  something like:

  submitForm: function(ev){
    form = $("#myForm");
    form.find("#the_textarea_field_id").val( this.editor.getContent() );
 }

3. Probably Dante is Sanitizing the existing divs of text generated by the previous implementation. In my case I've to clean the server side text to be loaded by Dante properly

**Comment by thangngoc89** [comment]
@michelson Thanks for your quick reply. I really don't know the `this.editor.getContent()` magic method. 
This project is awesome but still need improvements.
