### ISSUE TITLE
How to save posted image data with upload.php？

### ISSUE THREAD

**Issue by BaoHan** [michelson/Dante#42]
I want to save image with php method，but I cant get anything. How do I get the image url and store image in upload folder?

**Comment by michelson** [comment]
When you upload an image via Dante uploader, you will get a POST request to the server url defined in upload_url option on Dante initialization.
So , your php app should receive that POST request with the image data, not an url. with that data you have to do the upload in php and return to that request the url of your uploaded data, so Date will now that the url returned by your php script is the url to be replaced in the <img> tag on the interface.
I don't do PHP anymore, but in ruby a simple example would be:

```ruby
  # Handle POST-request (Receive data, save the uploaded file and return url of upload image)
  post "/upload_image" do
    name = params['file'][:filename] 
    path = File.join(File.dirname(__FILE__), '/uploads/images', name)
    File.open(path, "wb") do |f|
      f.write(params['file'][:tempfile].read)
    end
    return "/uploads/images/#{name}"
  end
```

**Comment by thangngoc89** [comment]
@michelson  don't forget about the recently upload callback :D

**Comment by BaoHan** [comment]
I found the problem -- forget to restart server ! sad:( 
here is simple php code :
//upload.php
<? php
move_uploaded_file($_FILES["file"]["tmp_name"], "upload/" . $_FILES["file"]["name"]);
 echo "upload/" . $_FILES["file"]["name"];
?>

**Comment by michelson** [comment]
great! , if you found more issues on this , please reopen this issue or submit new one

best!

**Comment by saranghills** [comment]
Wonderful! It was this small piece of information that I missed I guess. Or maybe I was not thinking clearly when you mentioned $_POST in your documentation. I have managed to do both : storing of the image, also the file (will have to improve my code, but successful in the basic features)

Now trying to figure out a way to list the edited pieces and edit them again. :)
