### ISSUE TITLE
Heading options are not working properly on Firefox (mac)

### ISSUE THREAD

**Issue by akkias** [michelson/Dante#43]

**Comment by akkias** [comment]
+ when I do bower install dante --save-dev, it does not automatically adds dante to index.html
+ Will it work fine if I add js/css from dist folder?

**Comment by michelson** [comment]
Hi @akkias , please clarify what you mean by Heading options are not working properly on Firefox ,even better if you can upload image.

what bower --save-dev suppose to do ? I really don't use bower , maybe my bower integration is very clumsy. btw, the index.html is not added into bower manifest, only the js files. that's what you looking for ?

if you use the files at dist should work fine.

**Comment by akkias** [comment]
![screen-shot-2015-02-07-at-1 36 33-am](https://cloud.githubusercontent.com/assets/340839/6091366/d9206b28-aece-11e4-991e-4e22d62366be.jpg)

**Comment by michelson** [comment]
@akkias Thanks for this report, indeed there is a bug when using blockquote.

I will check this up asap

Best
