### ISSUE TITLE
Can someone please explain how store_url and upload_url works.

### ISSUE THREAD

**Issue by akkias** [michelson/Dante#44]

**Comment by michelson** [comment]
Hi @akkias , you can find an explanation here in issue #42 

best

**Comment by akkias** [comment]
Thanks @michelson and how to save editor data with store_url?

I am not wrong then post_url == controller_url?

**Comment by michelson** [comment]
store_url will just send the post text via POST method , so it depends on how you want to submit your information , will could have an endpoint on with the data is received and the entry is updated
