### ISSUE TITLE
I seem to be unable to have two dante editors running at the same time

### ISSUE THREAD

**Issue by esperancaJS** [michelson/Dante#46]
This might be just my noobness.
I do give them different ids..

Thank you so much for everything once again @michelson !

**Comment by michelson** [comment]
yes probably it won't work, 

thanks for reporting @PedroEsperanca , I will check this asap

**Comment by zackgilbert** [comment]
Any momentum on this? Would love to see this become a reality.

**Comment by michelson** [comment]
ouch , not yet!, since we really don't need this feature this request will have to wait unless someone takes this challenge, it can't be so complicated. I'm sorry for the delay on this.

**Comment by zackgilbert** [comment]
Ha. Fair enough. Thanks!
