### ISSUE TITLE
Image URI issue

### ISSUE THREAD

**Issue by akkias** [michelson/Dante#47]
Hello Michelson,

Sorry troubling u again n again... :)

Now the issue is when I am uploading an image it getting converted into BASEURI and in background i am saving that image with it's original file name therefore I am unable to view that image after upload.

Could you explain how to handle this situation.

**Comment by michelson** [comment]
Hi @akkias , dont't worry.

after upload the image where is keept ?  is it visible from some path ? 
let' say localhost:8888/images/name.jpg ? if it so the upload response where the file is uploaded sould return that path.

best ?

**Comment by akkias** [comment]
Yes, I can view that file by hitting some url like localhost:8888/uploads/images/name.jpg
but I am not able to call that image in saved data because I am saving editor data by doing editor.getContent() which returns BASEURI.

**Comment by akkias** [comment]
So what we are doing is we collecting data from response.all and I think I am probably wrong there.

**Comment by michelson** [comment]
the upload process is different from editor.getContent and save interval, when you upload an image through Dante uploader , Dante expect that the server response of that upload returns the image path, that's it, like localhost:8888/uploads/images/name.jpg, if it's so Dante will handle the image display properly

**Comment by michelson** [comment]
check the image server example ```bundle exec rackup config.ru```

**Comment by akkias** [comment]
I am using PHP (Laravel) and kinda stuck on that thing only :(

**Comment by akkias** [comment]
If you don't mind, can you elaborate how to handle and retrive editor data.

**Comment by michelson** [comment]
I personally don't use auto save, so how I do is listen to the form submit event , and then i call `editor.getContent()` and I pass that value to my form text input before submit. 
something like:

```javascript
    btn = form.find(".btn.submit")
    btn.on('click', function( event ) {
        $('form').find("#post_content_input").val(editor.getContent());
        $('form').submit()
    })
```

**Comment by thangngoc89** [comment]
@akkias I'm using Laravel 5.0 to handle Dante upload and here is my code : 
```
public function store(uploadFileRequest $request)
    {
        $file = $request->file('file');

            $destination = storage_path().'/uploads/';
            $file->move($destination, 'random_file_name_here');

         echo 'http://example.com/image.jpg';
    }
```

**Comment by akkias** [comment]
Yay! It worked! thanks much Michelson

**Comment by akoury** [comment]
hey @thangngoc89 can you tell me how are you using Dante in laravel? i cant get it to work. Thanks!
