### ISSUE TITLE
Is there is a way to add custom HTML snippets ?

### ISSUE THREAD

**Issue by PedroEsperanca** [michelson/Dante#48]
I tried by editing the HTML directly but dantejs seems to filter out and format new elements

**Comment by michelson** [comment]
yep , Dante will filter custom html and that's fine, if you want to allow custom elements you will have to hack directly on the editor code. in cleanContents()

given the heuristics of the editor it's complicated to allow custom html as is, maybe this elements could exists into figure element and be treated like a kind of embed.

but right now there aren't any plans to implement any kind of custom html element besides emped. 
I guess you could tackle this right now implementing some oembed rendering with the custom output you want , if so you will have to implement you own oembed endpoints.

regards!

**Comment by PedroEsperanca** [comment]
Oh! Somehow only saw your response yesterday.
Sure I'll give cleanContents() a look soon :)

regards!
