### ISSUE TITLE
How can I programmatically set content?

### ISSUE THREAD

**Issue by Nesvet** [michelson/Dante#49]

**Comment by michelson** [comment]
Hi @Nesvet , 
the easiest way should be a $(editor.el).html("hello") . where editor is your Dante.editor instance.

could you go further on explaining what are you trying to do in order to be more helpfull?.

**Comment by Nesvet** [comment]
Hi, @michelson.

That's enough, thank you.

**Comment by creativeprogramming** [comment]
Doing this works but destroys the editor (eg. no more tooltip, no more + button on new line) and if i try to call .restart() or .render() i get the initial values and not the content i'm trying to set 

I'm trying to save getContent() on  history.pushstate and restore it on browser back button using popstate

**Comment by creativeprogramming** [comment]
Ok found the working way:

`$(dante_editor.el).find(".section-inner").html("Restored html")`

**Comment by creativeprogramming** [comment]
Anyway i fear? Is there some case where sections are more than one?

**Comment by creativeprogramming** [comment]
Update, I'd to add jQuery("#editor").unbind(); to my hack to make it work properly (a sort of raw destroy of event handlers to avoid multiple invokation if re-initialized

```javascript
function setDanteContent(html){
     $(dante_editor.el).html(html);
     dante_editor = new Dante.Editor(
            {
                api_key: "omissis",
                el: dante_editor.el,
                upload_url: "/ajax/upload",
                store_url: "/ajax/saveItemBody" + "?id=" + window.editingItemId,
                suggest_url: "/ajax/suggest",
                store_success_handler: dante_store_success,
                debug: false
            }
    );
    dante_editor.start();
    jQuery(dante_editor.el).unbind();
}
```

**Comment by michelson** [comment]
Hi , Dante does not make many assumptions on how to set content , it just initialize the content present on `$el`. When I want to display previous content, i just use something like this
```erb
<div id="editor">
  <%= partial "readme.md" %>
</div>
```   

in the same way, if you are going to initialize content from js, you must set it first to the DOM and then initialize Dante. it should work fine.

I will use a "js class" to avoid re-initialization
```coffeescript
class MyEditor 
   constructor: ->
      @editor = new Dante.Editor ...

   render: ->
      @editor.start()
  
   other_func: ->
     @editor.someThingElse()
 ```

then somewhere in the code

```js
$(document).ready ()->
  ed = MyEditor.new
  ed.render()
```

**Comment by creativeprogramming** [comment]
Yes,  but I need to be able to do it more and more times in the same 'single page application', as I may want to load different articles, different template via AJAX, localStorage API, history API, always without reloading the webpage or re-initializing the editor.

I think other developers too may find this useful, please consider some testing about dynamically changing the content on your Dante editor, it's a pity that such awesome product is made just for 'server side rendered pages' and not highly  'single page applications' (see: appshell paradigm suggested by google too)
