### ISSUE TITLE
Change stylesheet name from .css.scss to .scss and avoid problems in Rails4

### ISSUE THREAD

**Issue by felipefunes** [michelson/Dante#51]

**Comment by michelson** [comment]
Mr @felipefunes !
which kind of problems are you facing with Rails4 and stylesheet naming?
I'm currently using Dante on a Rails4 app in production without troubles.

could you paste the error or describe the problem in more detail?

best!

**Comment by felipefunes** [comment]
It's not a big deal, just to clean the message:

DEPRECATION WARNING: Extra .css in SCSS file is unnecessary.

https://github.com/rails/sass-rails/blob/1ddfbc9883d51a676d273822f42ca2c7023382ea/lib/sass/rails/importer.rb#L97

**Comment by michelson** [comment]
ah! I have not noticed that, it definitely it will be fixed on the next release
buena cumpita!

**Comment by felipefunes** [comment]
:) Un placer

**Comment by cristianferrarig** [comment]
:dancers:

**Comment by cristianferrarig** [comment]
solo para no quedar fuera :D

**Comment by michelson** [comment]
jajaja , gracias por el aporte :+1:

**Comment by felipefunes** [comment]
@cristianferrarig :dancer:

**Comment by michelson** [comment]
fixed in 0.0.11
