### ISSUE TITLE
Have to install eventmachine 1.0.4 for install dev env

### ISSUE THREAD

**Issue by julianfox** [michelson/Dante#54]
Hi,
Just for info, i has to update the Gemfile for change the version of eventmachine 1.0.3 > 1.0.4
I got this error with eventmachine 1.0.3: https://github.com/eventmachine/eventmachine/issues/553

**Comment by michelson** [comment]
Hi @julianfox , thanks for reporting this, We'll upgrade deps for the next release

Best!
