### ISSUE TITLE
Appropriate request method for saving

### ISSUE THREAD

**Issue by Flyr1Q** [michelson/Dante#65]
Why are you using POST method for updating, which is not really RESTful? It seems like PUT method would be much more appropriate.
And it would be nice if we could define keys for params in request, when updating. Or may be you can define events (like 'changed'), so we can override form submit by ourselves?

I apologize if this functionality has already exist, i did't found that.
PS: Thanks for your editor

**Comment by talgautb** [comment]
:+1:

**Comment by michelson** [comment]
good , idea, maybe the send method could be configurable with options such as POST | PUT.
patches are welcome

best!
