### ISSUE TITLE
ummm , exactly how do i set and get the post title ?

### ISSUE THREAD

**Issue by Pandahisham** [michelson/Dante#67]
by default there seems to be no difinite place for the title , i tried enabling the title_palceholder , it it didn't do anything , help needed please

**Comment by michelson** [comment]
Hi @Pandahisham , the title is just a h3 element that have a default text (the placeholder) in case the content is empty. the default placeholder text is "Title", check the image below. note that title is not an additional field, it's just an element inside the text for empty content.

![image](http://cl.ly/aVOa/Image%202015-04-02%20at%201.41.06%20PM.png)

**Comment by Pandahisham** [comment]
got it
