### ISSUE TITLE
Enhancement , making it work with sidecomments plugin 

### ISSUE THREAD

**Issue by Pandahisham** [michelson/Dante#68]
https://github.com/aroc/side-comments is a nice plugin that can be adapted with this , passing a datetime as a section-id , will make it unique , i will try to implement this and send a pull request if i have time

**Comment by Pandahisham** [comment]
i  changed the template , but the editor ignores them , why ?

**Comment by michelson** [comment]
Hi @Pandahisham I don't know what changes are you making , need more context.

some tips:

Note that you need to modify the files that are located in app/assets, and use a local webserver that comes with Dante for development . look the readme on *development* section

Also take a look at function ```addClassesToElement``` in editor.js.coffee, I guess you can add there the data attribute with the unique id, also look at utils.js.coffee file the funciton utils.generateUniqueName() that function can help with the unique naming.

good luck with this, It could be a very nice addition !

I will look forward for any updates on this

best!

**Comment by michelson** [comment]
in fact there is already an unique name attribute for each element, I've forgotten that

**Comment by Pandahisham** [comment]
hacking on it

**Comment by Pandahisham** [comment]
got it working , simply added a section id with the unique name variable
passed on , however i am not sure if it will be striped of during
sanitization process , plz look into it

**Comment by michelson** [comment]
Hi @Pandahisham that's great
I think the sanitization process will remove id attributes , but how about use the existing name attribute instead id attr ? would sidebar plugin works if you select by name?

**Comment by hkucukali** [comment]
Hi @Pandahisham, I'll be very happy if you share with us how you did. If integrated, that feature empowers the dante editor to build an open-source Medium-like experience.
