### ISSUE TITLE
Image Upload in grids

### ISSUE THREAD

**Issue by djyadav** [michelson/Dante#72]
Can you suggest some way to upload images into a grid ( if they are uploaded together).

Like as on

> if 2 uploaded together, then they get wrapped  into a div
> if 3 uploaded , then they wrapped into a div 
> then we can handle their width accordingly.

**Comment by michelson** [comment]
Hi @djyadav , it would be a really cool addition! I will assign this to the 0.1.0 milestone
thanks for the suggestion!

**Comment by akkias** [comment]
Can you check editor of maptia.com for reference?

**Comment by michelson** [comment]
Hi @akkias , maptia UI looks really awesome! I will take a closer look when implement this feature. I've seen similar behavior when upload more than one image in medium.com

**Comment by akkias** [comment]
Nice! it would be more nicer if you could add insert location button maptia :smile: :smile:

**Comment by akkias** [comment]
Hey, are you guys working on this.

**Comment by michelson** [comment]
not yet

**Comment by akkias** [comment]
Okay

**Comment by kargnas** [comment]
+1

**Comment by hkucukali** [comment]
+1

**Comment by jomarbarnobal** [comment]
+1
