### ISSUE TITLE
Undo error when removing link

### ISSUE THREAD

**Issue by tianshuo** [michelson/Dante#73]
To reproduce this bug:
1. Make a link,
2. select the text, press the link button, the link disappears
3. Press ctrl-z, bug appears: the text is duplicated

**Comment by michelson** [comment]
sorry, I can't reproduce error, But I've seen problems on UI when undo
which browser do you use ?

**Comment by tianshuo** [comment]
Chrome on mac. Try these steps:

1. Make a link,
2. select the text, press the link button, the link disappears
3. Select the text again, make a new link.
4. Press ctrl-z multiple times until bug appears: the text is duplicated
