### ISSUE TITLE
Content is editable when viewing

### ISSUE THREAD

**Issue by akkias** [michelson/Dante#74]
Hi Michelson,

I am saving my content in db and the html is editable.

can you please tell me how can I stop content being editable?

**Comment by michelson** [comment]
Hi @akkias , how are you saving content ?

if you use the `editor.getContent()` function you will get only the content inside the editable block.

**Comment by akkias** [comment]
I am getting the content which is inside the editable block but the problem here is....
when I am adding a caption to the image(selected) and leave it like that only and saves the content then I get all the tags including figcaption(contenteditable=true) in the data.

**Comment by julianfox** [comment]
Hey same for me

**Comment by michelson** [comment]
fixed in lates version check http://michelson.github.io/Dante/non_editable.html example
