### ISSUE TITLE
Cannot copy/paste Image + data

### ISSUE THREAD

**Issue by akkias** [michelson/Dante#79]
Hi,
I was trying to copy/paste data from another site to our editor and I have found quite a big bug.
I can copy and past textual content but I cannot do same with images, editor literally stops working post pasting the image.

Can you please it address this ASAP.

**Comment by michelson** [comment]
seems to be a dup of #33 
can you send me an example of the html content that are you trying to paste ?

**Comment by akkias** [comment]
http://www.bcmtouring.com/cms/ladakh-winter-travel-guide/

Can you also check console for the error

it gives me this error : dante-editor.js:60 Uncaught TypeError: Cannot read property 'childNodes' of undefined

**Comment by michelson** [comment]
fixed in 0.0.14
