### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by lorenkp** [michelson/Dante#80]
Hey guys,

What is your setup for posting to a file upload service via the single upload_url? I'm having trouble figuring out how to integrate with any of the common upload services.

**Comment by michelson** [comment]
have you seen the options:

   - *upload_url:* default: /uploads.json
   - *upload_callback*

**Comment by lorenkp** [comment]
I figured out how to sync this up with cloudinary—had to include some parameters in a query string. 

The upload_callback contains the url to the image now hosted on the server. How do I stick this url into the newly created img tag in the editor?

Thanks!

**Comment by michelson** [comment]
Hi @lorenkp , could you make it work ?
BTW, the upload callback have to return the url of the image, the editor will handle the rest
