### ISSUE TITLE
enhancement: How to pass a pre-existing body to the editor?

### ISSUE THREAD

**Issue by seoyoochan** [michelson/Dante#85]
There was a option for a pre-existing title, but not body.
This is really needed for editing mode.
when I edit my article, it needs to display its persistent data.

**Comment by seoyoochan** [comment]
I just found that `store_url` stores everything in `section-inner` element, which means it stores 'title' and 'body'. this leads to this problem: it does not store the title and body separately. 

There are 2 approaches for attaching pre-existing data transferred by server
   1) attach each title and body at its own markup ( you should back up separately beforehand )
   2) attach the whole inside `section-inner` element (title + body) and attach at the same element ( current Dante.js does send the whole. so what you need to do is just fixing how to render it )

I find the first approach is ideal, but I went the second for my convenience.

Go to `Editor.prototype.initialize`
-  add `var preContent`
-  add below
```
preContent = opts.preContent || '';`
this.preContent = preContent;
```
- Go to `Editor.prototype.getContent`
- Add this below `Editor.prototype.getContent`
```

    Editor.prototype.renderPreContent = function() {
        return this.preContent;
    };
```
- Go to `Editor.prototype.template`
- Replace the inside with this
```
if (this.preContent.length > 0) {
	return "<section class='section--first section--last'> <div class='section-divider layoutSingleColumn'> <hr class='section-divider'> </div> <div class='section-content'> <div class='section-inner layoutSingleColumn'> " +
            this.renderPreContent()
            + "</div> </div> </section>";
} else {
	return "<section class='section--first section--last'> <div class='section-divider layoutSingleColumn'> <hr class='section-divider'> </div> <div class='section-content'> <div class='section-inner layoutSingleColumn'> " + (this.disable_title ? '' : this.renderTitle()) + " <p class='graf graf--p'>" + this.body_placeholder + "<p> </div> </div> </section>";	
}
```

**Comment by michelson** [comment]
Hi , @seoyoochan , 
the easiest way should be a `$(editor.el).html("your content")` . where editor is your Dante.editor instance.
or put the content in the html like

`<div id="editor">
 your content
</div>
`

**Comment by seoyoochan** [comment]
@michelson  thanks for your response.
I want to contribute to maintain and enhance Dante too, how can I help?
I fixed a bug which is behind image gets deleted when deleting text. how can I send my commit?

**Comment by michelson** [comment]
Hi @seoyoochan , thanks for your interest! 
the best way to collaborate is making a pull request

thanks!

**Comment by michelson** [comment]
@seoyoochan , I've saw the PR you made , thanks a lot for your effort!
I will review them and try to merge it in this week.
best regards!
