### ISSUE TITLE
Dash, curly quotes, space replacing

### ISSUE THREAD

**Issue by riseremi** [michelson/Dante#91]
Hi guys, thank you for the great editor!
I lack those features from the title. Original medium.com editor automatically replaces two minuses (--) by dash (—), turns "straight quotes" into “curly quotes”.

The last feature is something strange, but I really love it:

```
Hello.| World
      ^ caret
```

If you press Space key now, editor will overwrite existing space and caret will be placed right here:

```
Hello. |World
       ^ caret
```

Hope you understand me. Good luck with this project! :)

**Comment by michelson** [comment]
Hi @riseremi , I see , those are subtle features. Will be in our roadmap sooner or later :)

Best!
