### ISSUE TITLE
Can we set timeout for uploads?

### ISSUE THREAD

**Issue by asonawan** [michelson/Dante#92]

**Comment by asonawan** [comment]
I mean how to set timeout for large uploads?

**Comment by michelson** [comment]
I think you can set the timeout from server side, does make sense to you ?

**Comment by akkias** [comment]
oh! I need to check it once...because I am using heroku service and they have 30sec timeout for uploads bt as u suggested I need to check on server side...

**Comment by michelson** [comment]
I will close this , reopen or create another ticket if you need help on this
