### ISSUE TITLE
Quote/Blockquote can't be removed once created 

### ISSUE THREAD

**Issue by mrgray** [michelson/Dante#94]
So basically if you create a quote, you can't *unquote* it. Is it a bug or intended behaviour?

**Comment by mrgray** [comment]
Ah, my bad, seems be to be on the to-do list!

**Comment by michelson** [comment]
no worries, @mrgray , it's fine to keep this issue in the **issues** section of the repo :+1:

**Comment by mrgray** [comment]
Ha, thanks @michelson! I'll try and patch it over the weekend when I have some free time. By the way I see that you added support for adding buttons in 0.0.11, is there a way to remove them though? I want to avoid overriding the default config.

**Comment by michelson** [comment]
Cool!, that would be great @mrgray , just ask if you need help on that patch.

To override the default buttons you have to use the **base_widgets** option, this option is an array , by default is initialised to ["uploader", "embed", "embed_extract"].

**Comment by mrgray** [comment]
Will do @michelson.

Na, I meant would it be possible to remove one of the formatting buttons i.e. bold, italics, etc. I want to disable italics and the capability to link.

**Comment by michelson** [comment]
sorry, I misunderstood that one.

But yes, you can override the editor default buttons, just use the **buttons** option , the defaults are ['bold', 'italic', 'h2', 'h3', 'h4', 'blockquote', 'createlink']

cheers

**Comment by michelson** [comment]
fixed!
