### ISSUE TITLE
Get rid of Dante-added classes

### ISSUE THREAD

**Issue by jerriep** [michelson/Dante#95]
Hi,

When Dante saves a file (or I use the `getContent()` method), the HTML contains a bunch of CSS classes which I assume is added for the editor:

```
<h3 class="graf graf--h3" name="4ps3df5hfr">This is a title</h3>
<p class="graf graf--p is-selected" name="ga17tlnmi">This is a test pararaph</p>
<p class="graf graf--p graf--empty graf--last" name="bzkl8oajor"><br></p>
```

For my purposes, when I save to the database I only want plain HTML, i.e. without the `id` and `class` tags. Is there a way to return the edited HTML without any of those classes?

Thanks

**Comment by michelson** [comment]
Hi @jerriep , 
You could sanitize in before save , on client or server side. but you could loose the default styles and the styles for specific elements generated when you use images or embeds. So maybe is not a good idea to do that.
Tell us how it goes,
Best

**Comment by jerriep** [comment]
Cool, thanks. Do I need to write the code to sanitize it myself, or is there a method I can call on the editor to do it for me?

**Comment by michelson** [comment]
Yes, you need to write it yourself , you can use the Sanitize function, that is included in Dante, just before the content is saved to the server.
Take a look at https://github.com/gbirke/Sanitize.js 

best!

**Comment by jerriep** [comment]
Great stuff thanks. I will write something to sort it out. If not on the client side, then on the server side. Thanks for the help.

**Comment by michelson** [comment]
Cool , would be great to add it then to the wiki for reference.

best!

**Comment by Jaza** [comment]
Here's what I'm doing to get the current content from Dante as sanitized text, for the purpose of putting it into a textarea (for form submission):

```javascript
var editor = new Dante.Editor({
  el: elem,
  upload_url: null,
  debug: false
});
editor.start();

var c = editor.cleanContents($(elem)
    .find('.section-inner')
    .clone())
  .html()
  .replace(/\<br\>\<\/p\>/g, '</p>')
  .replace(/ class=\"[^\"]+\"/g, '');
```

I know it's a bit hacky, would be more elegant to use Sanitize.js again, instead of getting rid of the `p` classes (and unwanted trailing `br` tags) with regex. But this is a quick and easy way to do it.

**Comment by jerriep** [comment]
We decided to store the documents as Markdown, so the conversion from HTML to Markdown automatically cleaned up the HTML.

**Comment by michelson** [comment]
Hi @jerriep , how do you convert the markdown back to HTML in order to display dante styles ? 
media and embeds will be lost in that case right ?

**Comment by jerriep** [comment]
Actually there seems to be some problems with Media embeds. 

As far as I understand the person I am doing the development for (Marc) has reached out to you regarding some requirements we have for Dante...

**Comment by michelson** [comment]
Hi @jerriep , yes indeed
