### ISSUE TITLE
Two paragraphs created when editor is started with no content

### ISSUE THREAD

**Issue by bazaglia** [michelson/Dante#97]
When I start the editor with no content (`<div id="editor"></div>`), two paragraphs are created. If I click in the second one and start typing, the placeholder doesn't disappear. Also, the (+) button doesn't show up when the second paragraph is clicked.

![dante-bug](https://cloud.githubusercontent.com/assets/6966980/10904749/af2acfd2-81fc-11e5-80c0-827b52f27839.png)

**Comment by akkias** [comment]
Hi bazaglia,

So if you open dante-editor.js and go to line no 615 where template has been defined,
then at the end of the line you can see that the paragraph tag has not been closed by mistake you just need to close that.

Cheers!

**Comment by bazaglia** [comment]
Hey @akkias that's true! Fixed. Thank you! Should we submit a PR?

**Comment by michelson** [comment]
Hi @bazaglia , yes you should, it would be great :)

**Comment by akkias** [comment]
@michelson I tried pushing the code but couldn't. Could you please tell me how can I check in my changes
